# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52ecdc4eaa63d8f11efd818a27d10365c3688cafe2fce5165b890b69808fd54eb267e1a4dfcdb204ea829654e4fbb677d405d45126e632325e400048331d5054

test:
  secret_key_base: d2716dc34d35035e8f21dc79195f61650b5b2ee13140b5c642bb5117c3d4622fb6c277417640f73ed9086a553b8f853f6e325c85c3c02a1b8d0e4197a05e48a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
